"""Set ON DELETE SET NULL for public_secrets.shared_secret_id

Revision ID: 2b08773e9ad2
Revises: bcd598c154eb
Create Date: 2024-12-16 09:04:57.938112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b08773e9ad2'
down_revision = 'bcd598c154eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_secrets', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    with op.batch_alter_table('shared_secrets', schema=None) as batch_op:
        batch_op.alter_column('period',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=5),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_secrets', schema=None) as batch_op:
        batch_op.alter_column('period',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)

    with op.batch_alter_table('public_secrets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
