"""empty message

Revision ID: 79df0be66f66
Revises: 9594cee9c628
Create Date: 2024-10-19 10:01:14.682774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79df0be66f66'
down_revision = '9594cee9c628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_secrets', schema=None) as batch_op:
        batch_op.alter_column('time_to_send',
               existing_type=postgresql.TIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_secrets', schema=None) as batch_op:
        batch_op.alter_column('time_to_send',
               existing_type=postgresql.TIME(),
               nullable=False)

    # ### end Alembic commands ###
