"""Update foreign key in history_payments to set user_id and plan_id to NULL on deletion

Revision ID: 9594cee9c628
Revises: 440e109a8ae4
Create Date: 2024-10-07 11:01:31.860515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9594cee9c628'
down_revision = '440e109a8ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_payments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('card_last_four',
               existing_type=sa.CHAR(length=4),
               type_=sa.String(length=4),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'plans', ['plan_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history_payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('card_last_four',
               existing_type=sa.String(length=4),
               type_=sa.CHAR(length=4),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
