"""Added ip_address to LoginHistory

Revision ID: bcd598c154eb
Revises: 050f65e80cc0
Create Date: 2024-10-21 10:46:32.166479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd598c154eb'
down_revision = '050f65e80cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True))

    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
