"""Add deleted_confirm column to SharedSecret

Revision ID: c6b597f2310e
Revises: f8944db0821e
Create Date: 2024-09-05 11:36:28.537669

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6b597f2310e'
down_revision = 'f8944db0821e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.alter_column('plan',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['plan'])

    with op.batch_alter_table('shared_secrets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_confirm', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('shared_secrets', schema=None) as batch_op:
        batch_op.drop_column('deleted_confirm')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('description',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('plan',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
