"""Add cascading delete to Secret and SharedSecret

Revision ID: f545f9d0aa67
Revises: c6b597f2310e
Create Date: 2024-09-05 14:43:21.215930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f545f9d0aa67'
down_revision = 'c6b597f2310e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_secrets', schema=None) as batch_op:
        batch_op.drop_constraint('shared_secrets_secret_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'secrets', ['secret_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_secrets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('shared_secrets_secret_id_fkey', 'secrets', ['secret_id'], ['id'])

    # ### end Alembic commands ###
