"""empty message

Revision ID: fd886c082df2
Revises: 027d2ffc3806
Create Date: 2024-09-16 12:55:30.542203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd886c082df2'
down_revision = '027d2ffc3806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secrets', schema=None) as batch_op:
        batch_op.drop_constraint('secrets_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secrets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('secrets_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
